### ISSUE TITLE
Gluster Write-Behind translator can cause data corruption

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#110]
The problem was first discovered when running the smb2.rw.rw1 test on samba-integration. The issue was reported upstream at
https://bugzilla.samba.org/show_bug.cgi?id=14486
and then on gluster at
https://github.com/gluster/glusterfs/issues/1501

The problem was determined to be caused by the Write-Behind translator which is enabled by default on gluster and therefore used by the samba vfs_glusterfs plugin. This gives rise to data corruption issues.

**Comment by anoopcs9** [comment]
Test results for sequential write using _**fio**_ via kernel CIFS mount - [seq-write](https://anoopcs.fedorapeople.org/seq-write)

**Comment by anoopcs9** [comment]
Upstream issue for adding pass-through volume set option for write-behind translator: https://github.com/gluster/glusterfs/issues/1565

**Comment by spuiuk** [comment]
We have considered the following options.

1) Disable write-behind using glfs_set_xlator_option()
At the moment, no code exists to disable the translator through the glfs_set_xlator_option. An option,  pass-through, was made available for other performance translators allowing applications to disable these translators on a per connection basis. Unfortunately, this is not available for write-behind at the moment.
A new feature request has been created for glusterfs

2) Check for presence of write-behind translator from vfs_glusterfs and print out warning message in the log file.
There is no easy way to determine the loaded translators on the glusterfs translator stack. To do this, we will need to call glfs_get_volfile() and then parse the volfile to determine if the translator has been loaded.

At the moment, we plan on documenting the data corruption issue in the vfs_glusterfs man page asking users to disable the translator.

**Comment by spuiuk** [comment]
Issue has been fixed in upstream samba and in glusterfs.

Commits -

Samba:
08f8f665d40 docs-xml/manpages: Add warning about write-behind translator for vfs_glusterfs
2a49ccbcf5e s3-vfs_glusterfs: refuse connection when write-behind xlator is present
7d846cd178d s3: modules: vfs_glusterfs: Fix leak of char **lines onto mem_ctx on return.
a51cda69ec6 s3-vfs_glusterfs: always disable write-behind translator

Glusterfs:
8c0a1047c write-behind: Implement 'pass-through' option
