### ISSUE TITLE
Samba nightly builds for CentOS 8

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#121]
We have nightly glusterfs builds available at
http://artifacts.ci.centos.org/gluster/nightly/devel/8/x86_64/

We should consider building samba-nightly builds for CentOS 8 as well.

**Comment by obnoxxx** [comment]
As detailed in https://github.com/gluster/samba-integration/issues/134#issuecomment-779456588 , it is already done for Gluster (for both centos version and Gluster version). We could mimic this approach for samba RPMs.

**Comment by obnoxxx** [comment]
The centos8 builds have been established by https://github.com/gluster/centosci/pull/142 and #138 - The next nightly run should create the artifacts yum repository.
