### ISSUE TITLE
Create nightly RPM builds for latest samba upstream release branches

### ISSUE THREAD

**Issue by obnoxxx** [gluster/samba-integration#134]
Build RPMs nightly for Samba upstream release branch heads for the latest, or few latest release branches.

**Comment by obnoxxx** [comment]
For the Gluster nightly RPMs, this is already established.

It is realised with two yaml files there:

This is the generic job that can invoke the build script with a few input parameters (git branch, centos version, ...): https://github.com/gluster/centosci/blob/master/jobs/build-rpms.yml

And this is the concrete job that sets up runs for the various combinations of git branches and centos versions:
https://github.com/gluster/centosci/blob/master/jobs/nightly-rpm-builds.yml

Not saying we need to be able to do it this way, but it might be good to mimic it.

**Comment by anoopcs9** [comment]
Waiting on https://github.com/gluster/centosci/pull/151. . .
