### ISSUE TITLE
smbtorture test failure in smb2.create

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#136]
The new changes in pathref for samba are causing failures in smb2.create. These are regressions.

The failing tests are

gluster-vol-replicate:
samba3.smb2.create.mkdir-dup

gluster-vol-disperse:
samba3.smb2.create.brlocked
samba3.smb2.create.delete
samba3.smb2.create.leading-slash
samba3.smb2.create.impersonation
samba3.smb2.create.acldir
samba3.smb2.create.mkdir-dup
samba3.smb2.create.dir-alloc-size

**Comment by spuiuk** [comment]
I have found the cause of the regressions for the smb2.create.mkdir-dup test.
https://gitlab.com/spuiuk/samba/-/commit/f79197aeaf5a9aa2616ea7468bb1e9b498a98b17

I have yet to determine how this affects the other tests which were failing especially with the dispersed volume.

**Comment by anoopcs9** [comment]
[Nightly test run](https://ci.centos.org/job/gluster_samba-integration/) is back running successfully again. Thanks for root causing and providing the patch upstream.
