### ISSUE TITLE
Samba(4.14 ): pathrefs opened with O_PATH flag

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#145]
Opened for discussion on the changes to upstream samba which could radically affect the performance of Samba with glusterfs as the backing filesystem.

**Changes to Samba 4.14:**
(https://www.samba.org/~slow/doc/The_New_VFS.html)
Every file pointer in Samba with GlusterFS backend will result in an open(O_RDONLY) call made. This will negatively affect performance on these setups.

**Reasons for change:** 
SMB2 operations mostly operate on handles. Current code ends up degrading handle based smb2 calls to path based. Code changes will allow samba to better use handle based operations used by SMB2.

**Changes:**
Samba's internal file handle opens a O_PATH reference to the file. This pathref fd is used only for path reference and no IO.
For filesystems which do not support O_PATH, samba opens the file as root using O_RDONLY.

**Potential Problems:**
1) A simple readdir call will end up opening a O_RDONLY handle to every file in the directory which can cause performance issues.(This needs to be confirmed with the latest samba versions)
2) pathref fds opened in this fallback mode could result in additional security issues.

**Additional information:**

**O_PATH flag to open() call:**
(https://lwn.net/Articles/543295/)
Returns a fd which can be used for 2 purposes.
a) indicate location in the filesystem tree.
b) perform operations purely on a fd level. (eg: close, fchdir, fstat, dup, fcntl(F_DUPD, F_GETFD, F_SETFD, openat)

File not opened and file operations and operations like read, write, fchmod, fchown, fgetxattr fail with error EBADF.

**Comment by spuiuk** [comment]
O_PATH doesn't seem to actually work with upstream glusterfs for now.
https://github.com/gluster/glusterfs/issues/2717

**Comment by spuiuk** [comment]
I did an experiment to test the behaviour of running open() with the O_PATH flag on a file and deleting the underneath file.

With a normal open, while the fd is open, deleting a file results in only the dentry being removed, ie. remove any way to access the file from the fs. But the inode which contains the file is only removed when all open fds are closed ie. the file is not actually removed from the disk and continues to occupy the space on the disk.

 We wanted to know if the behaviour is the same when the file is opened with the O_PATH flag. 

To test this, the following steps were run.
1) Create an 100 M image file using dd.
2) Format it with ext4
3) mount if with the '-o loop' option onto a mount point.
4) Create a 50 Mb file with the dd command.
5) Use a tool calling open on the file and pausing to allow you to run other operations on another terminal.
6) On terminal 2, use df to check if file occupies the space on the mount point, delete file, call df again to check file space consumed.
7) on terminal 1, press a key to close the open fd.
8) check the disk space consumed with the df command.

Results:
With a file opened with O_PATH, the behaviour is exactly the same as a file opened without O_PATH. The file with an open fd when unlinked from the fs, continues to occupy disk space until it is eventually deleted.

**Comment by spuiuk** [comment]
Test 2:  Perform the same test as above but on a fuse filesystem.

[root@client1 ~]# mount -t glusterfs storage0:/vol-replicate /mnt

[root@client1 mnt]# dd if=/dev/zero of=test bs=1M count=2048
2048+0 records in
2048+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 19.8378 s, 108 MB/s

[root@client1 ~]# df -h /mnt
Filesystem               Size  Used Avail Use% Mounted on
storage0:/vol-replicate   12G  2.4G  9.7G  20% /mnt

[root@client1 ~]# ./openfile /mnt/test 
Opening file /mnt/test    -- Done
-- At this point, the tool freezes while it waits for a keypress on the terminal. The rest of the test is run on a second terminal.

#We check to see if the file occupies disk space.
[root@client1 ~]# df -h /mnt
Filesystem               Size  Used Avail Use% Mounted on
storage0:/vol-replicate   12G  2.4G  9.7G  20% /mnt

# We delete the file - remember the fd  to this file is open on terminal 1
[root@client1 ~]# rm /mnt/test
rm: remove regular file '/mnt/test'? y

# The file now no longer occupies disk space.
[root@client1 ~]# df -h /mnt
Filesystem               Size  Used Avail Use% Mounted on
storage0:/vol-replicate   12G  311M   12G   3% /mnt

Retrying with open without the O_PATH flag this time.

[root@client1 ~]# dd if=/dev/zero of=/mnt/test bs=1M count=2048
2048+0 records in
2048+0 records out

[root@client1 ~]# df -h /mnt
Filesystem               Size  Used Avail Use% Mounted on
storage0:/vol-replicate   12G  2.4G  9.7G  20% /mnt

#Open file on a different terminal with the openfile tool
[root@client1 ~]# rm /mnt/test; ls -l /mnt/test
rm: remove regular file '/mnt/test'? y
ls: cannot access '/mnt/test': No such file or directory

[root@client1 ~]# df -h /mnt
Filesystem               Size  Used Avail Use% Mounted on
storage0:/vol-replicate   12G  2.4G  9.7G  20% /mnt
#Close the fd on the other terminal
[root@client1 ~]# df -h /mnt
Filesystem               Size  Used Avail Use% Mounted on
storage0:/vol-replicate   12G  311M   12G   3% /mnt

As seen, on a file with an open fd, unlinking the file doesn't actually remove the file from the disk(glusterfs) until the open fd has closed. This however is not the case when the file is opened with the O_PATH flag and will cause a problem on shares exported with the vfs_glusterfs_fuse module. We will have to treat open calls as being made with O_PATH support disabled.

**Comment by spuiuk** [comment]
[openfile.tar.gz](https://github.com/gluster/samba-integration/files/7086502/openfile.tar.gz)

Tool used to perform the two tests above.

**Comment by anoopcs9** [comment]
Unless there are any missed edge cases we are complete on functional side of things to work with new VFS interface from Samba. Please go through the sambaXP [presentation](https://sambaxp.org/fileadmin/user_upload/sambaxp2023-Slides/CS_sXP23_DFSvianewVFS.pdf) to know where we stand. Future efforts to validate the performance impact could be driven from project's new home https://github.com/samba-in-kubernetes/sit-test-cases/.
