### ISSUE TITLE
samba-build: Cannot re-run builds after test faiure

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#168]
Cannot re-run builds after test failure.

It fails with the following error message:

TASK [set.version : Switch to branch checkout at commit hash] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["git", "checkout", "-b", "master-7a077f152aa3e1e09b4228ae24780fa613540a68", "7a077f152aa3e1e09b4228ae24780fa613540a68"], "delta": "0:00:00.003785", "end": "2021-05-12 22:52:38.740238", "msg": "non-zero return code", "rc": 128, "start": "2021-05-12 22:52:38.736453", "stderr": "fatal: A branch named 'master-7a077f152aa3e1e09b4228ae24780fa613540a68' already exists.", "stderr_lines": ["fatal: A branch named 'master-7a077f152aa3e1e09b4228ae24780fa613540a68' already exists."], "stdout": "", "stdout_lines": []}

I had to delete directory /tmp/samba-build to be able to re-run the make build command.

Should this be handled by the ansible script instead?

**Comment by anoopcs9** [comment]
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["git", "checkout", "-b", "master-7a077f152aa3e1e09b4228ae24780fa613540a68", "7a077f152aa3e1e09b4228ae24780fa613540a68"], "delta": "0:00:00.003785", "end": "2021-05-12 22:52:38.740238", "msg": "non-zero return code", "rc": 128, "start": "2021-05-12 22:52:38.736453", "stderr": "fatal: A branch named 'master-7a077f152aa3e1e09b4228ae24780fa613540a68' already exists.", "stderr_lines": ["fatal: A branch named 'master-7a077f152aa3e1e09b4228ae24780fa613540a68' already exists."], "stdout": "", "stdout_lines": []}

This is exactly the catch I mentioned earlier while raising the PR. 
 
> I had to delete directory /tmp/samba-build to be able to re-run the make build command.

You could have also deleted the branch :-)

> Should this be handled by the ansible script instead?

I have raised a [PR](https://github.com/gluster/samba-integration/pull/170) to tackle this problem with git hash.
