### ISSUE TITLE
CI failure for nightly build job

### ISSUE THREAD

**Issue by anoopcs9** [gluster/samba-integration#173]
I am opening this issue as a place holder for recent failures we have seen with test and nightly build jobs.

All those [failures](https://ci.centos.org/job/gluster_samba-integration/649/console) were initially triggered by a [patch](https://github.com/gluster/centosci/commit/3cbdc2802493c7aa284557741cc5cdcde7ee962f) that went into [gluster/centosci](https://github.com/gluster/centosci) repository where it introduced a new mandatory argument _--release_ to `cico` command which is used by `get-node.sh` script commonly invoked within our jobs([samba-integration.yml](https://github.com/gluster/centosci/blob/main/jobs/samba-integration.yml) and [nightly-samba-rpm-builds.yml](https://github.com/gluster/centosci/blob/main/jobs/nightly-samba-rpm-builds.yml)).

Above mentioned patch expects an argument to _--release_ option in the form of a variable `CENTOS_VERSION`. Unlike [samba-integration](https://github.com/gluster/centosci/blob/main/jobs/samba-integration.yml) job our [nightly build](https://github.com/gluster/centosci/blob/main/jobs/nightly-samba-rpm-builds.yml) job luckily had this variable already defined. Thus all those jobs([gluster_samba-build-rpms-centos7-master](https://ci.centos.org/view/Gluster/job/gluster_samba-build-rpms-centos7-master/), [gluster_samba-build-rpms-centos7-v4-14-test](https://ci.centos.org/view/Gluster/job/gluster_samba-build-rpms-centos7-v4-14-test/) and [gluster_samba-build-rpms-centos7-v4-13-test](https://ci.centos.org/view/Gluster/job/gluster_samba-build-rpms-centos7-v4-13-test/)) running on a CentOS 7 host continued to run successfully(apart from some spurious failures 2-3 times) despite the new change. Also for the time being I made a [change](https://github.com/gluster/centosci/pull/165/commits/44e9c0888023ac4c6521b9781e90283ad7d73743) in our samba-integration job to run on a CetnOS 7 host and now we have some real [failure](https://ci.centos.org/job/gluster_samba-integration/654/consoleFull) with mounting GlusterFS volume :-(. See #175 

But when it comes to CentOS 8 and upstream vagrant, things become much difficult. Various installation and run-time errors are seen and have to be fixed as mentioned [here](https://github.com/vagrant-libvirt/vagrant-libvirt#installation) in vagrant-libvirt plugin official docs. I am trying to consolidate those steps which are relevant right now for CentOS 8 and have included some basic changes to [nightly-samba-builds.sh](https://github.com/gluster/centosci/blob/main/jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh) script(not enough :-/). Please add your suggestions/steps in case you manage to run any of our jobs successfully on a C8 host along with additional package requirements so that we could include those in our helper scripts([samba-integration-centos-ci-tests.sh](https://github.com/gluster/samba-integration/blob/centos-ci/samba-integration-centos-ci-tests.sh) and [nightly-samba-builds.sh](https://github.com/gluster/centosci/blob/main/jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh)).

**Comment by anoopcs9** [comment]
See below for the steps based on official docs using which I could successfully run core(setting up and bringing up cluster using vagrant-libvirt plugin) of our jobs defined for samba-integration and nightly builds on CentOS 8:
```
# Install extra requirements
dnf -y install cmake rsync zlib-devel

# Download krb5 sources and recompile
mkdir -p /tmp/krb5/sources/
cd /tmp/krb5
dnf download --sources krb5-libs
rpm2cpio *.rpm | cpio -imdV
tar xf *.tar.gz -C sources/ --strip-components=1
cd sources/src
./configure
make
cp -P lib/crypto/libk5crypto.* /opt/vagrant/embedded/lib64/

# Download libssh sources and recompile
mkdir -p /tmp/libssh/sources
cd /tmp/libssh
dnf download --sources libssh
rpm2cpio *.rpm | cpio -imdV
tar xf *.tar.xz -C sources/ --strip-components=1
mkdir build
cd build
cmake ../sources -DOPENSSL_ROOT_DIR=/opt/vagrant/embedded/
make
cp lib/libssh* /opt/vagrant/embedded/lib64

cd ~
# Finally install vagrant-libvirt plugin
CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH vagrant plugin install vagrant-libvirt
```

**Comment by spuiuk** [comment]
If we can't find a proper maintained release of vagrant, if it would be better to have a copr(CentOS8 equivalent) with a vagrant release for centos8.

**Comment by anoopcs9** [comment]
I found a Fedora COPR [vagrant](https://copr.fedorainfracloud.org/coprs/pvalena/vagrant/) project maintained by one of the admins for vagrant in [Fedora pagure](https://src.fedoraproject.org/rpms/vagrant). I will update if I can get things to work on CentOS 8 with el8 vagrant rpms from the above COPR repository.
