### ISSUE TITLE
Enable SELinux

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#41]
At the moment, we work around SELinux issues by setting SELinux to permission mode in 
vagrant/ansible/roles/ctdb.setup/tasks/main.yml
for the cluster nodes.

I captured the audit.log generated on doing a "systemctl restart ctdb" after applying changes proposed #40. This will allow us to investigate this further.

**Comment by spuiuk** [comment]
type=NETFILTER_CFG msg=audit(1586347196.753:4845): table=filter family=2 entries=104

type=SYSCALL msg=audit(1586347196.753:4845): arch=c000003e syscall=54 success=yes exit=0 a0=5 a1=0 a2=40 a3=6add10 items=0 ppid=31901 pid=31902 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-multi" subj=system_u:system_r:iptables_t:s0 key=(null)

type=PROCTITLE msg=audit(1586347196.753:4845): proctitle=69707461626C6573002D4900494E505554002D690065746832002D64003139322E3136382E3132332E3131002D6A0044524F50

type=AVC msg=audit(1586347196.760:4846): avc:  denied  { nlmsg_read } for  pid=31905 comm="ss" scontext=system_u:system_r:ctdbd_t:s0 tcontext=system_u:system_r:ctdbd_t:s0 tclass=netlink_tcpdiag_socket permissive=1

type=AVC msg=audit(1586347196.760:4846): avc:  denied  { module_request } for  pid=31905 comm="ss" kmod="net-pf-16-proto-4-type-2" scontext=system_u:system_r:ctdbd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=1

type=SYSCALL msg=audit(1586347196.760:4846): arch=c000003e syscall=46 success=yes exit=92 a0=3 a1=7fffbaa3ffb0 a2=0 a3=7fffbaa3f8e0 items=0 ppid=31903 pid=31905 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="ss" exe="/usr/sbin/ss" subj=system_u:system_r:ctdbd_t:s0 key=(null)

type=PROCTITLE msg=audit(1586347196.760:4846): proctitle=7373002D746E0073746174650065737461626C697368656400737263005B3139322E3136382E3132332E3131

type=NETFILTER_CFG msg=audit(1586347196.783:4847): table=filter family=2 entries=105

type=SYSCALL msg=audit(1586347196.783:4847): arch=c000003e syscall=54 success=yes exit=0 a0=5 a1=0 a2=40 a3=1e35da0 items=0 ppid=31913 pid=31914 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="iptables" exe="/usr/sbin/xtables-multi" subj=system_u:system_r:iptables_t:s0 key=(null)

type=PROCTITLE msg=audit(1586347196.783:4847): proctitle=69707461626C6573002D4400494E505554002D690065746832002D64003139322E3136382E3132332E3131002D6A0044524F50

type=SERVICE_STOP msg=audit(1586347196.860:4848): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=smb comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

type=SERVICE_START msg=audit(1586347196.907:4849): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=ctdb comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

type=SERVICE_STOP msg=audit(1586347196.907:4850): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=ctdb comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

type=SERVICE_START msg=audit(1586347198.277:4851): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=ctdb comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

**Comment by anoopcs9** [comment]
> type=AVC msg=audit(1586347196.760:4846): avc: denied { nlmsg_read } for pid=31905 comm="ss" scontext=system_u:system_r:ctdbd_t:s0 tcontext=system_u:system_r:ctdbd_t:s0 tclass=netlink_tcpdiag_socket permissive=1
> 
> type=AVC msg=audit(1586347196.760:4846): avc: denied { module_request } for pid=31905 comm="ss" kmod="net-pf-16-proto-4-type-2" scontext=system_u:system_r:ctdbd_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=1

Good..only two AVCs. These are fine I guess.

Let me then update #40 to leave SELinux under Enforcing mode.
