### ISSUE TITLE
make test is always run twice

### ISSUE THREAD

**Issue by anoopcs9** [gluster/samba-integration#64]
From last [nightly run](https://ci.centos.org/job/gluster_samba-integration/160/consoleFull):

> 06:28:24 TASK [client.test.prep : Run tests] ********************************************
> 06:28:36 changed: [client1]
> 06:28:36 
> 06:28:36 TASK [client.test : Run tests] *************************************************
> 06:28:47 changed: [client1]

Why are we running `make test` in both _client.test.prep_ and _client.test_ ?

**Comment by spuiuk** [comment]
This is a bug for which PR #66 created.
