### ISSUE TITLE
Two packages provide libgfrpc.so.0()(64bit)

### ISSUE THREAD

**Issue by spuiuk** [gluster/samba-integration#88]
I have been attempting to setup the cluster and hit the following error when installing glusterfs-server and two different packages provide it.

TASK [node.prep : Install GlusterFS rpms] **************************************
fatal: [storage1]: FAILED! => {"changed": true, "changes": {"installed": ["glusterfs-server"], "updated": []}, "msg": "Error: Package: glusterfs-server-20200609.955bfd5-0.0.el7.x86_64 (gluster-nightly-master)\n           Requires: libgfrpc.so.0()(64bit)\n           Available: glusterfs-libs-6.0-29.el7.x86_64 (base)\n               libgfrpc.so.0()(64bit)\n           Available: libgfrpc0-20200609.955bfd5-0.0.el7.x86_64 (gluster-nightly-master)\n
..

The error message properly formatted.

Error: Package: glusterfs-server-20200609.955bfd5-0.0.el7.x86_64 (gluster-nightly-master)
           Requires: libgfrpc.so.0()(64bit)
           Available: glusterfs-libs-6.0-29.el7.x86_64 (base)
               libgfrpc.so.0()(64bit)
           Available: libgfrpc0-20200609.955bfd5-0.0.el7.x86_64 (gluster-nightly-master)
               libgfrpc.so.0()(64bit)

**Comment by spuiuk** [comment]
Attempted to fix issue with PR 89. However now hit another dependency issue when installing samba-vfs-glusterfs.

Error: Package: samba-vfs-glusterfs-20200609.210724.ddac6b2-1.el7.1.x86_64 (samba-nightly-master)
           Requires: glusterfs-api >= 3.4.0.16

# yum install glusterfs-api
Does not find any packages.

So retrying after disabling the exclude
# yum install --disableexcludes=all glusterfs-api
returns
Package glusterfs-api-6.0-29.el7.x86_64 is obsoleted by libgfapi0-20200609.955bfd5-0.0.el7.x86_64 which is already installed

**Comment by spuiuk** [comment]
Looking at
http://artifacts.ci.centos.org/gluster/nightly/master/7/x86_64/

I see that the last glusterfs-api was built on 20200608.
We also see one instance of 
libgfapi0-20200609.955bfd5-0.0.el7.x86_64.rpm

**Comment by anoopcs9** [comment]
An overhaul was done, see https://github.com/gluster/glusterfs/issues/1126

Following renames was done:
- glusterfs-api -> libgfapi0
- glusterfs-api-devel -> libgfapi-devel

glusterfs-libs replaced with following packages:
- libglusterfs0
- libgfrpc0
- libgfxdr0
- libgfchangelog0

glusterfs-devel replaced with following packages:
- libglusterfs-devel
- libgfrpc-devel
- libgfxdr-devel
- libgfchangelog-devel

**Comment by spuiuk** [comment]
Anoop and I had a discussion on the call today. The packages were renamed in the nightly gluster build according to gluster/glusterfs#1126. This means that we now have this sticky situation where the same dependency is provided by two separate packages. This is causing both problems mentioned in this issue.

I proposed that the fix for this case should be provided on the glusterfs end possibly by bumping the provided library version numbers and the corresponding dependencies on the new packages being built.

**Comment by anoopcs9** [comment]
> Anoop and I had a discussion on the call today. The packages were renamed in the nightly gluster build according to [gluster/glusterfs#1126](https://github.com/gluster/glusterfs/issues/1126). This means that we now have this sticky situation where the same dependency is provided by two separate packages. This is causing both problems mentioned in this issue.
> 
> I proposed that the fix for this case should be provided on the glusterfs end possibly by bumping the provided library version numbers and the corresponding dependencies on the new packages being built.

Recently uploaded [patch](https://review.gluster.org/#/c/glusterfs/+/24563/) should fix above issue

**Comment by anoopcs9** [comment]
> Attempted to fix issue with PR 89. However now hit another dependency issue when installing samba-vfs-glusterfs.
> 
> Error: Package: samba-vfs-glusterfs-20200609.210724.ddac6b2-1.el7.1.x86_64 (samba-nightly-master)
> Requires: glusterfs-api >= 3.4.0.16
> 
> # yum install glusterfs-api
> Does not find any packages.
> 
> So retrying after disabling the exclude
> # yum install --disableexcludes=all glusterfs-api
> returns
> Package glusterfs-api-6.0-29.el7.x86_64 is obsoleted by libgfapi0-20200609.955bfd5-0.0.el7.x86_64 which is already installed

#90 should fix above issue. Therefore removing previously linked PR #89

**Comment by spuiuk** [comment]
Fixed by adding some obsoletes in the gluster nightly build rpms.
